### ISSUE TITLE
Channel Authentication endpoint

### ISSUE THREAD

**Issue by m-teslya** [abhishiv/pusher-lite#3]
Hello
following pusher API documentation, we can set authentication endpoint for presence- and private- channels. Maybe I overlooked ability to set it when reviewing code, but I did not found it.
Cheers
           Michael

**Comment by abhishiv** [comment]
Are you sure you aren't confusing the sever api with client lib? Link to documentation?

**Comment by m-teslya** [comment]
I think, this is related to client lib
http://pusher.com/docs/authenticating_users#authEndpoint

**Comment by abhishiv** [comment]
True, but this the browser client. 

In our case, authentication is handled [automatically](https://github.com/abhishiv/pusher-node-client/blob/master/lib/pusher-node-client.coffee#L25), so it sends the correct auth data when you subscribe to a channel.

**Comment by m-teslya** [comment]
Hmm, so I can't use this lib in case, where auth should be controlled by another app?

**Comment by abhishiv** [comment]
Honestly, it doesn't make sense to me why you would let some other app do authentication for a server lib. On the browser you do it because you don't wanna expose your pusher credentials to the end user.

Why can't you just do this?

```
pusher_client = new PusherClient
  appId: (process.env.PUSHER_APP_ID or app_id)
  key: (process.env.PUSHER_KEY or pusher_key)
  secret: (process.env.PUSHER_SECRET or pusher_secret)
```

**Comment by m-teslya** [comment]
I was going to use this lib for unit testing. I have server API, so, I need custom auth endpoint to cover my client functionality. Looks like this just not a my lib :). 
Thank you for your time!
