### ISSUE TITLE
Cannot call method 'sendUTF' of undefined

### ISSUE THREAD

**Issue by chrisdlangton** [abhishiv/pusher-lite#9]
just using subscribe - cant work as connection is never defined as a property of the object anywhere in the codebase.

library has been unmaintained for years, no surprise it was unfinished - pathetic its listed officially by Pusher.com

**Comment by abhishiv** [comment]
wrong! 

You are probably not waiting for 'connect' event.

If it's an actual issue I would appreciate if someone writes a more descriptive issue.

**Comment by leggetter** [comment]
@chrisdlangton Seems to be listed as a community library. If you're looking for a Node client I'd try https://github.com/dirkbonhomme/pusher-client-node

If pusher-node-client isn't working at all then I'll see if I can get it removed from the list of libraries.

**Comment by leggetter** [comment]
@abhishiv is there anything that could be done to provide better feedback in the scenario that you've described?
